name: podberi_ru
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-48.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.5 #стейт менеджер и управление темой
  shared_preferences: ^2.2.2 #маленький кэш
  go_router: ^12.1.1 #роутинг в приложении
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9 #для svg картинок
  isar: ^3.1.0+1 #локальное хранилище
  isar_flutter_libs: ^3.1.0+1 #локальное хранилище
  path_provider: ^2.1.1
  expandable_page_view: ^1.0.17 #для перелистывания списка как страницы
  flutter_custom_clippers: ^2.1.0
  boxy: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/nav_bar_icons/
    - assets/icons/
    - assets/images/
    - assets/logos/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Geologica
      fonts:
        - asset: assets/fonts/geologica/Geologica-Regular.ttf
          style: normal

