name: podberi_ru
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.5 #стейт менеджер и управление темой
  riverpod_generator: ^2.3.5 #генератор кода
  riverpod_annotation: ^2.3.0

  isar: ^3.1.0+1 #локальное хранилище
  isar_flutter_libs: ^3.1.0+1 #локальное хранилище

  go_router: ^12.1.1 #роутинг в приложении
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9 #для svg картинок
  expandable_page_view: ^1.0.17 #для перелистывания списка как страницы (page view с авторазмером)
  flutter_custom_clippers: ^2.1.0 #замена clipper'a который рисует нестандартные виджеты на экране
  boxy: ^2.1.3 #расширение для верстки с сливерами (SliverContainer)
  sliver_tools: ^0.2.12 #расширение для верстки с сливерами (SliverStack)

  pretty_dio_logger: ^1.3.1 #красивый логгер для дио (надо убрать потом)
  freezed_annotation: ^2.4.1
  json_annotation: 4.8.1
  dio: ^5.4.0
  alice: ^0.4.1 #HTTP-инспектор (удалить перед публикацией )
  get_it: ^7.6.4
  connectivity_plus: ^5.0.2 #проверка подключения к сети
  flutter_html: ^3.0.0-beta.2 #пакет для отображения текста с html тэгами
  webview_flutter: ^4.4.4 #пакет для открытия веб страниц внутри приложения
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  json_serializable: 6.6.2
  freezed: ^2.4.5 # генерация кода
  isar_generator: ^3.1.0+1

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/nav_bar_icons/
    - assets/icons/promo_codes_icons/
    - assets/icons/error_icons/
    - assets/icons/
    - assets/images/promo_codes_images/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Geologica
      fonts:
        - asset: assets/fonts/geologica/Geologica-Regular.ttf
          style: normal

